# Generated by Django 3.1.7 on 2021-03-10 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='body',
        ),
    ]
